apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend_deploy.yaml
  - backend_service.yaml
  - frontend_deploy.yaml
  - frontend_env.yaml
  - frontend_ingress_sikademo_com.yaml
  - frontend_ingress.yaml
  - frontend_service.yaml
  - redis_sts.yaml
  - redis_service.yaml
